name: Srtool build

on: push

jobs:
  srtool:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chain: ["westend"]
    steps:
      - uses: actions/checkout@v2
      - name: Srtool build
        id: srtool_build
        uses: chevdor/srtool-actions@draft
        with:
          chain: ${{ matrix.chain }}
      - name: Summary
        run: |
          echo Summary:
          echo "- version: ${{ steps.srtool_build.outputs.version }}"
          echo "- info: ${{ steps.srtool_build.outputs.info }}"
          echo "- prop: ${{ steps.srtool_build.outputs.proposal_hash }}"
      - name: Digest # this step is split from the previous for now to debug
        run: |
          echo '${{ steps.srtool_build.outputs.json }}' | jq
          echo '${{ steps.srtool_build.outputs.json }}' | jq > ${{ matrix.chain }}-runtime-digest.json
      - name: Install latest stable
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true
      - name: Install subwasm
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: "--git https://gitlab.com/chevdor/subwasm"
      - name: Install tera-cli
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: "--git https://github.com/guangie88/tera-cli"
      - name: Show WASM information
        shell: bash
        run: subwasm info ${{ steps.srtool_build.outputs.wasm }}
      - name: Extract the metadata
        shell: bash
        run: subwasm meta ${{ steps.srtool_build.outputs.wasm }}
      - name: Check the metadata diff
        shell: bash
        run: subwasm diff ${{ steps.srtool_build.outputs.wasm }} --chain-b ${{ matrix.chain }}
      - name: Build report
        shell: bash
        run: |
          echo '${{ steps.srtool_build.outputs.json }}' >> /tmp/data.json
          tera --json /tmp/data.json --file templates/srtool_report.md >> report.md
      - name: Store artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.chain }}-runtime
          path: |
            report.md
            ${{ matrix.chain }}-runtime-digest.json
            "${{ steps.srtool_build.outputs.wasm }}"
