name: Srtool build

on: push

jobs:
  srtool:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chain: ["westend"]
    steps:
      - uses: actions/checkout@v2
      - name: Srtool build
        id: srtool_build
        uses: chevdor/srtool-actions@draft
        with:
          chain: ${{ matrix.chain }}
      - name: Summary
        run: |
          echo Summary:
          echo - version: ${{ steps.srtool_build.outputs.version }}
          echo - info: ${{ steps.srtool_build.outputs.info }}
          echo - prop: ${{ steps.srtool_build.outputs.proposal_hash }}
          echo ${{ steps.srtool_build.outputs.json }} | jq
      - name: Install latest stable
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true
      - uses: actions-rs/cargo@v1
        with:
          command: install
          args: "--git https://github.com/guangie88/tera-cli"
      - name: Build report
        shell: bash
        run: |
          echo ${{ steps.srtool_build.outputs.json }} >> /tmp/data.json
          tera --json /tmp/data.json --file templates/srtool_report.md >> report.md

