name: Srtool build

on: push

jobs:
  srtool:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chain: ["westend"]
    steps:
      - uses: actions/checkout@v2
      - name: Srtool build
        id: srtool_build
        uses: chevdor/srtool-actions@draft
        with:
          chain: ${{ matrix.chain }}
          tag: nightly-2021-06-01
      - name: Summary
        run: |
          echo Summary:
          echo "- version: ${{ steps.srtool_build.outputs.version }}"
          echo "- info: ${{ steps.srtool_build.outputs.info }}"
          echo "- prop: ${{ steps.srtool_build.outputs.proposal_hash }}"
      - name: Digest
        run: |
          echo '${{ steps.srtool_build.outputs.json }}' | jq > ${{ matrix.chain }}-runtime-digest.json
          cat ${{ matrix.chain }}-runtime-digest.json

  install_cargo:
    runs-on: ubuntu-latest
    steps:
      - name: Install latest stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

  install_subwasm:
    runs-on: ubuntu-latest
    needs: install_cargo
    steps:
      - name: Install subwasm
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: "--git https://gitlab.com/chevdor/subwasm"

  install_tera:
    runs-on: ubuntu-latest
    needs: install_cargo
    steps:
      - name: Install tera-cli
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: "--git https://github.com/chevdor/tera-cli"

  subwasm:
    runs-on: ubuntu-latest
    needs: install_subwasm
    steps:
      - name: Show Runtime information
        shell: bash
        run: |
          subwasm info ${{ steps.srtool_build.outputs.wasm }}
          subwasm --json info ${{ steps.srtool_build.outputs.wasm }} > ${{ matrix.chain }}-info.json
      - name: Extract the metadata
        shell: bash
        run: |
          subwasm meta ${{ steps.srtool_build.outputs.wasm }}
          subwasm --json meta ${{ steps.srtool_build.outputs.wasm }} > ${{ matrix.chain }}-metadata.json
      - name: Check the metadata diff
        shell: bash
        run: |
          subwasm diff ${{ steps.srtool_build.outputs.wasm }} --chain-b ${{ matrix.chain }} > ${{ matrix.chain }}-diff.txt
          cat ${{ matrix.chain }}-diff.txt

  reports:
    runs-on: ubuntu-latest
    needs: ["install_tera", "srtool"]
    steps:
      - name: Build report for ${{ matrix.chain }}
        shell: bash
        run: |
          tera --template templates/srtool_report.md --env ${{ matrix.chain }}-runtime-digest.json >> ${{ matrix.chain }}-runtime-report.md

  artifacts:
    runs-on: ubuntu-latest
    needs: ["srtool", "subwasm", "reports"]
    steps:
      - name: Store artifacts for ${{ matrix.chain }}
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.chain }}-runtime-${{ github.ref }}
          path: |
            ${{ steps.srtool_build.outputs.wasm }}
            ${{ matrix.chain }}-runtime-digest.json
            ${{ matrix.chain }}-runtime-report.md
            ${{ matrix.chain }}-metadata.json
            ${{ matrix.chain }}-info.json
            ${{ matrix.chain }}-diff.txt
